
 GET http://localhost:5088/todos
###


 GET http://localhost:5088/todos/2
###

DELETE http://localhost:5088/todos/1
###

POST http://localhost:5088/todos
content-type: application/json

{
    "id": "2",
    "icon": "🍆",
    "title": "Hren",
    "description": "Boljshoj Hren",
    "color": "#00FF00",
    "isCompleted": true
}

###

PUT http://localhost:5088/todos/2
content-type: application/json

{
    "id": "2",
    "icon": "🍆",
    "title": "Boljshoj",
    "description": "Boljshoj Hren",
    "color": "#00FF00",
    "isCompleted": true
}
